(with (foo)
      ("display" "tell me something about the universe\n" #answer-to-the-universe)
      ("display" "tell me something about girls\n" #answer-of-girls)
      (set! me "SEE interpreter")
      ("display" "Who am I?\n" me)
      )
