(with (vec vlen vref vset t)
      (set! vec 6)
      (set! vlen 7)
      (set! vref 8)
      (set! vset 9)
      (set! t (vec 4 5 6 7 8))
      ("display" t)
      ("display" (vlen t))
      ("display" (vref t 3))
      (vset t 3 1)
      ("display" t)
      )
